name: build
on:
  push:
    paths-ignore:
      - "site/**"
      - "site/.nojekyll"
      - ".github/workflows/deploy-site.yml"
  pull_request:
    paths-ignore:
      - "site/**"
      - "site/.nojekyll"
      - ".github/workflows/deploy-site.yml"

permissions:
  contents: read

jobs:
  build-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - run: |
           docker build -f .github/docker/py.Dockerfile \
             --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
             --tag minigrid-docker .
      - name: Run tests
        run: docker run minigrid-docker pytest
      - name: Run doctest
        run: docker run minigrid-docker pytest --doctest-modules minigrid/

  build-old:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -f .github/docker/py-old.Dockerfile \
             --build-arg PYTHON_VERSION="3.10" \
             --tag minigrid-docker .
      - name: Run tests
        run: docker run minigrid-docker pytest
